services:
  - type: web
    name: jewpeter-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 # Or your preferred version
      - key: PORT
        value: 8000
